valor = input ('Digite algo: ')
print ('O tipo primitivo é: ', type(valor))
print ('Só tem espaços: ', valor.isspace())
print ('É alfanumerico? ', valor.isalnum())
print ('É alfabetico? ', valor.isalpha())
print ('Está em maiusculas? ', valor.isupper())
print ('Está em minusculas? ', valor.islower())
print ('É numerico? ', valor.isnumeric())
print ('Está capitalizada? ', valor.istitle())
